export const data = [
    {
        id: 2,
        country: "Włochy",
        accommodation: "Hotel",
        object: "Angelo",
        price: "2380",
        date: "28.01.2023 - 04.02.2023",
        skipass: "Nie",
        board: "Pełne",
        category: ["Wczasy ogólne"],
        startingDate: "01/28/2023",
        transport: "Dojazd własny/autokar"
    },
    {
        id: 4,
        country: "Włochy",
        accommodation: "Apartament",
        price: "1525",
        object: "Top Residence",
        date: "28.01.2023 - 04.02.2023",
        skipass: "Nie",
        board: "Bez wyżywienia",
        category: ["Wczasy ogólne"],
        startingDate: "01/28/2023",
        transport: "Dojazd własny/autokar"
    },
    {
        id: 7,
        country: "Włochy",
        accommodation: "Hotel",
        object: "Cevedale",
        price: "2849",
        date: "10.03.2023 - 19.03.2023",
        skipass: "Nie",
        board: "Pełne",
        category: ["Wczasy ogólne", "Ski 50+ aktywnie"],
        startingDate: "03/10/2023",
        transport: "Autokar w cenie"
    },
    {
        id: 8,
        country: "Włochy",
        accommodation: "Hotel",
        object: "Golf",
        price: "3349",
        date: "21.01.2023 - 28.01.2023",
        skipass: "Nie",
        board: "Pełne",
        category: ["Wczasy ogólne", "Wczasy ze szkółkami dla dzieci"],
        startingDate: "01/21/2023",
        transport: "Dojazd własny"
    },
    {
        id: 10,
        country: "Włochy",
        accommodation: "Apartament",
        object: "Derby Club",
        price: "1248",
        date: "28.01.2023 - 04.02.2023",
        skipass: "Nie",
        board: "Bez wyżywienia",
        category: ["Wczasy ogólne", "Wczasy ze szkółkami dla dzieci"],
        startingDate: "01/28/2023",
        transport: "Dojazd własny/autokar"
    },
    {
        id: 12,
        country: "Włochy",
        accommodation: "Hotel",
        object: "Pampeago",
        price: "2655",
        date: "28.01.2023 - 04.02.2023",
        skipass: "Nie",
        board: "Pełne",
        category: ["Wczasy ogólne", "Wczasy ze szkółkami dla dzieci"],
        startingDate: "01/28/2023",
        transport: "Dojazd własny/autokar"
    },
    {
        id: 14,
        country: "Włochy",
        accommodation: "Hotel",
        object: "Misurina",
        price: "2375",
        date: "11.03.2023 - 19.03.2023",
        skipass: "Nie",
        board: "Pełne",
        category: ["Wczasy ogólne"],
        startingDate: "03/11/2023",
        transport: "Dojazd własny/autokar"
    },
    {
        id: 15,
        country: "Włochy",
        accommodation: "Hotel",
        object: "Haus an der Luck",
        price: "2975",
        date: "24.02.2023 - 05.03.2023",
        skipass: "Nie",
        board: "Pełne",
        category: ["Wczasy ogólne"],
        startingDate: "02/24/2023",
        transport: "Autokar w cenie"
    },
    {
        id: 16,
        country: "Włochy",
        accommodation: "Hotel",
        object: "Solaris",
        price: "3698",
        date: "27.01.2023 - 05.02.2023",
        skipass: "Skipass",
        board: "Pełne",
        category: ["Wczasy ogólne", "Wczasy ze szkółkami dla dzieci"],
        startingDate: "01/27/2023",
        transport: "Autokar w cenie"
    },
    {
        id: 19,
        country: "Włochy",
        accommodation: "Apartament",
        object: "La Gran Becca",
        price: "2175",
        date: "10.03.2023 - 19.03.2023",
        skipass: "Nie",
        board: "Bez wyżywienia",
        category: ["Wczasy ogólne"],
        startingDate: "03/10/2023",
        transport: "Dojazd własny/autokar"
    },
    {
        id: 20,
        country: "Włochy",
        accommodation: "Hotel",
        object: "La Rocca Sport",
        price: "2625",
        date: "10.02.2023 - 19.02.2023",
        skipass: "Nie",
        board: "Tylko śniadania",
        category: ["Wczasy ogólne"],
        startingDate: "02/10/2023",
        transport: "Autokar w cenie"
    },
    {
        id: 21,
        country: "Włochy",
        accommodation: "Ośrodek sportowy",
        object: "Villaggio Dolomitico",
        price: "2950",
        date: "27.01.2023 - 05.02.2023",
        skipass: "Skipass",
        board: "Pełne",
        category: ["Obozy młodzieżowe"],
        startingDate: "01/27/2023",
        transport: "Autokar w cenie"
    },
    {
        id: 22,
        country: "Francja",
        accommodation: "Apartament",
        object: "Gentianes",
        price: "2125",
        date: "27.01.2023 - 05.02.2023",
        skipass: "Skipass",
        board: "Bez wyżywienia",
        category: ["Wczasy ogólne"],
        startingDate: "01/27/2023",
        transport: "Autokar w cenie"
    },
    {
        id: 9,
        country: "Włochy",
        accommodation: "Hotel",
        object: "Golf",
        price: "3349",
        date: "28.01.2023 - 04.02.2023",
        skipass: "Nie",
        board: "Pełne",
        category: ["Wczasy ogólne", "Wczasy ze szkółkami dla dzieci"],
        startingDate: "01/28/2023",
        transport: "Dojazd własny/autokar"
    },
    {
        id: 6,
        country: "Włochy",
        accommodation: "Hotel",
        object: "Cevedale",
        price: "2449",
        date: "04.02.2023 - 11.02.2023",
        skipass: "Nie",
        board: "Pełne",
        category: ["Wczasy ogólne", "Wczasy ze szkółkami dla dzieci"],
        startingDate: "02/04/2023",
        transport: "Dojazd własny/autokar"
    },
    {
        id: 23,
        country: "Francja",
        accommodation: "Apartament",
        object: "Gentianes",
        price: "2125",
        date: "03.03.2023 - 12.03.2023",
        skipass: "Skipass",
        board: "Bez wyżywienia",
        category: ["Wczasy ogólne"],
        startingDate: "03/03/2023",
        transport: "Autokar w cenie"
    },
    {
        id: 17,
        country: "Włochy",
        accommodation: "Hotel",
        object: "Solaris",
        price: "3749",
        date: "10.03.2023 - 19.03.2023",
        skipass: "Skipass",
        board: "Pełne",
        category: ["Wczasy ogólne"],
        startingDate: "03/10/2023",
        transport: "Autokar w cenie",
        additional_information: "Termin dla grup zorganizowanych",
    },    {
        id: 28,
        country: "Austria",
        accommodation: "Hotel",
        object: "Margarethenbad",
        price: "2350",
        date: "04.02.2023 - 11.02.2023",
        skipass: "Nie",
        board: "Pełne",
        category: ["Wczasy ogólne", "Wczasy ze szkółkami dla dzieci"],
        startingDate: "02/04/2023",
        transport: "Dojazd własny/autokar"
    },

    {
        id: 24,
        country: "Francja",
        accommodation: "Apartament",
        object: "Les Chalets L'Adonis",
        price: "2475",
        date: "09.12.2023 - 18.12.2023",
        skipass: "Skipass",
        board: "Bez wyżywienia",
        category: ["Wczasy ogólne"],
        startingDate: "[twelve]/09/2023",
        transport: "Autokar w cenie"
    },
    {
        id: 1,
        country: "Włochy",
        accommodation: "Hotel",
        object: "Angelo",
        price: "2670",
        date: "10.12.2022 - 17.12.2022",
        skipass: "Skipass",
        board: "Pełne",
        category: ["Wczasy ogólne"],
        startingDate: "[twelve]/10/2022",
        transport: "Dojazd własny/autokar"
    },
    {
        id: 25,
        country: "Francja",
        accommodation: "Apartament",
        object: "Les Chalets L'Adonis",
        price: "2650",
        date: "24.03.2023 - 02.04.2023",
        skipass: "Skipass",
        board: "Bez wyżywienia",
        category: ["Wczasy ogólne"],
        startingDate: "03/24/2023",
        transport: "Autokar w cenie"
    },
    {
        id: 26,
        country: "Francja",
        accommodation: "Apartament",
        object: "Front De Neige",
        price: "3080",
        date: "17.03.2023 - 26.03.2023",
        skipass: "Skipass",
        board: "Bez wyżywienia",
        category: ["Wczasy ogólne"],
        startingDate: "03/17/2023",
        transport: "Autokar w cenie"
    },
    {
        id: 27,
        country: "Austria",
        accommodation: "Hotel",
        object: "Margarethenbad",
        price: "2350",
        date: "28.01.2023 - 04.02.2023",
        skipass: "Nie",
        board: "Pełne",
        category: ["Wczasy ogólne", "Wczasy ze szkółkami dla dzieci"],
        startingDate: "01/28/2023",
        transport: "Dojazd własny/autokar"
    },
    {
        id: 29,
        country: "Czechy",
        accommodation: "Hotel",
        object: "Prom",
        price: "1550",
        date: "29.01.2023 - 03.02.2023",
        skipass: "Nie",
        board: "Pełne",
        category: ["Wczasy ogólne", "Wczasy ze szkółkami dla dzieci"],
        startingDate: "01/29/2023",
        transport: "Dojazd własny/autokar"
    },
    {
        id: 5,
        country: "Włochy",
        accommodation: "Hotel",
        object: "Cevedale",
        price: "2398",
        date: "28.01.2023 - 04.02.2023",
        skipass: "Nie",
        board: "Pełne",
        category: ["Wczasy ogólne", "Wczasy ze szkółkami dla dzieci"],
        startingDate: "01/28/2023",
        transport: "Dojazd własny/autokar"
    },
    {
        id: 3,
        country: "Włochy",
        accommodation: "Apartament",
        object: "Top Residence",
        price: "1845",
        date: "10.12.2022 - 17.12.2022",
        skipass: "Skipass",
        board: "Bez wyżywienia",
        category: ["Wczasy ogólne"],
        startingDate: "[twelve]/10/2022",
        transport: "Dojazd własny/autokar"
    },
    {
        id: 13,
        country: "Włochy",
        accommodation: "Hotel",
        object: "Misurina",
        price: "2585",
        date: "28.01.2023 - 04.02.2023",
        skipass: "Nie",
        board: "Pełne",
        category: ["Wczasy ogólne", "Wczasy ze szkółkami dla dzieci"],
        startingDate: "01/28/2023",
        transport: "Dojazd własny/autokar"
    },
    {
        id: 11,
        country: "Włochy",
        accommodation: "Apartament",
        object: "Derby Club",
        price: "1293",
        date: "04.02.2023 - 11.02.2023",
        skipass: "Nie",
        board: "Bez wyżywienia",
        category: ["Wczasy ogólne", "Wczasy ze szkółkami dla dzieci"],
        startingDate: "02/04/2023",
        transport: "Dojazd własny"
    },
    {
        id: 30,
        country: "Czechy",
        accommodation: "Hotel",
        object: "Prom",
        price: "698",
        date: "06.01.2023 - 08.01.2023",
        skipass: "Nie",
        board: "Pełne",
        category: ["Express narty"],
        startingDate: "01/06/2023",
        transport: "Autokar w cenie"
    },
    {
        id: 18,
        country: "Włochy",
        accommodation: "Hotel",
        object: "Solaris",
        price: "3598",
        date: "17.03.2023 - 26.03.2023",
        skipass: "Skipass",
        board: "Pełne",
        category: ["Wczasy ogólne"],
        startingDate: "03/17/2023",
        transport: "Autokar w cenie"
    },
    {
        id: 31,
        country: "Czechy",
        accommodation: "Hotel",
        object: "Prom",
        price: "698",
        date: "03.03.2023 - 05.03.2023",
        skipass: "Nie",
        board: "Pełne",
        category: ["Express narty"],
        startingDate: "03/03/2023",
        transport: "Autokar w cenie"
    },
];